import type { Article, Material, Launch, Report, SiscomexUpdate } from "@/types";

export const articles: Article[] = [
  {
    id: "1",
    slug: "guia-completo-importacao-brasil",
    title: "Guia completo para importar no Brasil em 2026",
    excerpt: "Tudo que você precisa saber sobre o processo de importação, desde a pesquisa de fornecedor até o desembaraço aduaneiro.",
    content: `## Introdução\n\nImportar no Brasil pode parecer complexo, mas com o conhecimento certo o processo se torna muito mais simples. Neste guia, vamos cobrir cada etapa do processo de importação.\n\n## Habilitação no RADAR\n\nO primeiro passo para importar é habilitar sua empresa no RADAR (Registro e Rastreamento da Atuação dos Intervenientes Aduaneiros). Este registro é obrigatório para qualquer empresa que deseje realizar operações de comércio exterior.\n\n## Classificação NCM\n\nA Nomenclatura Comum do Mercosul (NCM) é fundamental para determinar os impostos incidentes sobre a mercadoria importada. Cada produto tem um código específico de 8 dígitos.\n\n## Impostos na Importação\n\nOs principais impostos na importação são:\n\n- **II (Imposto de Importação)**: varia conforme a NCM\n- **IPI (Imposto sobre Produtos Industrializados)**: para produtos industrializados\n- **PIS e COFINS**: contribuições federais\n- **ICMS**: imposto estadual\n\n## Conclusão\n\nCom planejamento adequado e conhecimento das regulamentações, a importação pode ser uma excelente estratégia para reduzir custos e aumentar a competitividade.`,
    category: "Importação",
    thumbnail: "https://placehold.co/800x450/2E73B8/FFFFFF?text=Guia+Importação",
    publishedAt: "2026-03-20T10:00:00Z",
    readingTime: 8,
    author: "Equipe Mainô",
  },
  {
    id: "2",
    slug: "mudancas-legislacao-comex-2026",
    title: "Principais mudanças na legislação de comércio exterior em 2026",
    excerpt: "Confira as atualizações regulatórias que impactam importadores e exportadores brasileiros neste ano.",
    content: `## Novas Regulamentações\n\nO ano de 2026 trouxe importantes mudanças para o comércio exterior brasileiro. Vamos analisar as principais alterações.\n\n## Reforma Aduaneira\n\nA reforma aduaneira em curso prevê a simplificação dos processos de despacho aduaneiro, com digitalização completa dos documentos e redução dos prazos de liberação.\n\n## Novos Acordos Comerciais\n\nO Brasil avançou em novos acordos comerciais que impactam diretamente os importadores, com redução de tarifas para determinados produtos.`,
    category: "Legislação",
    thumbnail: "https://placehold.co/800x450/1C5B99/FFFFFF?text=Legislação+2026",
    publishedAt: "2026-03-18T10:00:00Z",
    readingTime: 6,
    author: "Equipe Mainô",
  },
  {
    id: "3",
    slug: "logistica-internacional-boas-praticas",
    title: "Boas práticas em logística internacional para reduzir custos",
    excerpt: "Estratégias comprovadas para otimizar sua cadeia logística internacional e reduzir custos operacionais.",
    content: `## Otimização Logística\n\nA logística internacional é um dos maiores desafios para importadores brasileiros. Custos de frete elevados e prazos de entrega longos impactam diretamente a competitividade.\n\n## Incoterms\n\nEscolher o Incoterm correto é fundamental. A diferença entre FOB e CIF, por exemplo, pode significar economias significativas dependendo do produto e fornecedor.\n\n## Consolidação de Cargas\n\nPara importadores com volumes menores, a consolidação de cargas (LCL) pode reduzir significativamente os custos de frete.`,
    category: "Logística",
    thumbnail: "https://placehold.co/800x450/033860/FFFFFF?text=Logística+Internacional",
    publishedAt: "2026-03-15T10:00:00Z",
    readingTime: 7,
    author: "Equipe Mainô",
  },
  {
    id: "4",
    slug: "tecnologia-transformando-comex",
    title: "Como a tecnologia está transformando o comércio exterior",
    excerpt: "Da inteligência artificial ao blockchain, as inovações tecnológicas que estão revolucionando o comex.",
    content: `## Transformação Digital no Comex\n\nO comércio exterior está passando por uma revolução tecnológica. Ferramentas digitais estão simplificando processos que antes exigiam semanas.\n\n## IA na Classificação Fiscal\n\nAlgoritmos de inteligência artificial já conseguem classificar mercadorias com alta precisão, reduzindo erros de NCM e as multas associadas.\n\n## Blockchain na Rastreabilidade\n\nA tecnologia blockchain oferece rastreabilidade completa da cadeia de suprimentos, aumentando a transparência e reduzindo fraudes.`,
    category: "Tecnologia",
    thumbnail: "https://placehold.co/800x450/092441/A3C9F0?text=Tecnologia+Comex",
    publishedAt: "2026-03-12T10:00:00Z",
    readingTime: 5,
    author: "Equipe Mainô",
  },
  {
    id: "5",
    slug: "despacho-aduaneiro-passo-a-passo",
    title: "Despacho aduaneiro: passo a passo completo",
    excerpt: "Entenda cada etapa do processo de despacho aduaneiro e como agilizar a liberação das suas mercadorias.",
    content: `## O que é o Despacho Aduaneiro\n\nO despacho aduaneiro é o procedimento pelo qual a autoridade aduaneira verifica a exatidão das informações declaradas pelo importador.\n\n## Etapas do Processo\n\n1. Registro da DI (Declaração de Importação)\n2. Conferência aduaneira\n3. Pagamento dos tributos\n4. Liberação da mercadoria\n\n## Canais de Parametrização\n\nApós o registro da DI, a mercadoria é parametrizada em um dos quatro canais: verde, amarelo, vermelho ou cinza.`,
    category: "Importação",
    thumbnail: "https://placehold.co/800x450/2E73B8/FFFFFF?text=Despacho+Aduaneiro",
    publishedAt: "2026-03-10T10:00:00Z",
    readingTime: 9,
    author: "Equipe Mainô",
  },
  {
    id: "6",
    slug: "ncm-erros-comuns-como-evitar",
    title: "NCM: os erros mais comuns e como evitá-los",
    excerpt: "Erros na classificação fiscal podem gerar multas e atrasos. Saiba como classificar corretamente suas mercadorias.",
    content: `## A Importância da Classificação Correta\n\nA classificação NCM incorreta é uma das principais causas de autuações fiscais no comércio exterior brasileiro.\n\n## Erros Mais Frequentes\n\n- Usar NCM genérica quando existe código específico\n- Ignorar as notas de seção e capítulo\n- Não atualizar classificações quando há mudanças na tabela\n\n## Como Evitar Problemas\n\nSempre consulte a TIPI (Tabela de Incidência do IPI) e as decisões do Comitê do Sistema Harmonizado.`,
    category: "Legislação",
    thumbnail: "https://placehold.co/800x450/1C5B99/FFFFFF?text=Classificação+NCM",
    publishedAt: "2026-03-08T10:00:00Z",
    readingTime: 6,
    author: "Equipe Mainô",
  },
  {
    id: "7",
    slug: "frete-internacional-como-negociar",
    title: "Como negociar fretes internacionais mais competitivos",
    excerpt: "Táticas e estratégias para obter melhores condições com transportadoras e agentes de carga.",
    content: `## Mercado de Fretes\n\nO mercado de fretes internacionais é dinâmico e complexo. Saber negociar pode gerar economias significativas.\n\n## Estratégias de Negociação\n\n- Consolidar volumes para ter maior poder de barganha\n- Estabelecer contratos anuais com transportadoras\n- Diversificar fornecedores de frete\n\n## Momento Certo de Contratar\n\nO timing da contratação é crucial. Fretes spot podem ser mais baratos em períodos de baixa demanda.`,
    category: "Logística",
    thumbnail: "https://placehold.co/800x450/41AE32/FFFFFF?text=Frete+Internacional",
    publishedAt: "2026-03-05T10:00:00Z",
    readingTime: 7,
    author: "Equipe Mainô",
  },
  {
    id: "8",
    slug: "siscomex-novidades-primeiro-trimestre-2026",
    title: "SISCOMEX: novidades do primeiro trimestre de 2026",
    excerpt: "Confira as principais atualizações e melhorias implementadas no sistema aduaneiro brasileiro.",
    content: `## Atualizações do SISCOMEX\n\nO SISCOMEX passou por importantes atualizações no primeiro trimestre de 2026, visando simplificar e modernizar os processos aduaneiros.\n\n## Nova Interface\n\nA Receita Federal lançou uma nova interface mais intuitiva para o SISCOMEX, facilitando o registro de declarações.\n\n## Integração com Nota Fiscal\n\nA nova versão permite integração direta com o sistema de Nota Fiscal Eletrônica, reduzindo a necessidade de preenchimento duplicado.`,
    category: "Tecnologia",
    thumbnail: "https://placehold.co/800x450/092441/A3C9F0?text=SISCOMEX+2026",
    publishedAt: "2026-03-02T10:00:00Z",
    readingTime: 5,
    author: "Equipe Mainô",
  },
  {
    id: "9",
    slug: "ex-tarifario-oportunidades",
    title: "Ex-tarifário: como aproveitar as oportunidades para reduzir impostos",
    excerpt: "Entenda o mecanismo do ex-tarifário e como ele pode reduzir significativamente o custo de importação de bens de capital.",
    content: `## O que é o Ex-tarifário\n\nO ex-tarifário é um mecanismo que permite a redução temporária do Imposto de Importação para bens de capital e bens de informática sem produção nacional equivalente.\n\n## Requisitos\n\nPara solicitar um ex-tarifário, é necessário demonstrar que o bem não possui similar nacional.\n\n## Processo de Solicitação\n\nO pedido é feito ao MDIC e passa por análise técnica antes de ser aprovado. O prazo médio é de 60 a 90 dias.`,
    category: "Importação",
    thumbnail: "https://placehold.co/800x450/2E73B8/FFFFFF?text=Ex-tarifário",
    publishedAt: "2026-02-28T10:00:00Z",
    readingTime: 8,
    author: "Equipe Mainô",
  },
];

export const materials: Material[] = [
  {
    id: "1",
    slug: "ebook-guia-importacao-iniciantes",
    title: "E-book: Guia de Importação para Iniciantes",
    description: "O guia completo para quem está começando no mundo da importação. Cobre desde habilitação RADAR até desembaraço aduaneiro.",
    type: "ebook",
    coverImage: "https://placehold.co/300x400/2E73B8/FFFFFF?text=E-book+Importação",
    downloadUrl: "#",
    publishedAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "2",
    slug: "infografico-impostos-importacao",
    title: "Infográfico: Impostos na Importação",
    description: "Visualização clara e objetiva de todos os impostos incidentes na importação brasileira.",
    type: "infografico",
    coverImage: "https://placehold.co/300x400/1C5B99/FFFFFF?text=Infográfico+Impostos",
    downloadUrl: "#",
    publishedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "3",
    slug: "guia-classificacao-ncm",
    title: "Guia Prático de Classificação NCM",
    description: "Manual detalhado para classificar corretamente suas mercadorias na Nomenclatura Comum do Mercosul.",
    type: "guia",
    coverImage: "https://placehold.co/300x400/033860/FFFFFF?text=Guia+NCM",
    downloadUrl: "#",
    publishedAt: "2026-03-05T10:00:00Z",
  },
  {
    id: "4",
    slug: "pdf-checklist-importacao",
    title: "Checklist Completo de Importação",
    description: "Lista de verificação com todos os documentos e etapas necessárias para uma importação bem-sucedida.",
    type: "pdf",
    coverImage: "https://placehold.co/300x400/092441/A3C9F0?text=Checklist",
    downloadUrl: "#",
    publishedAt: "2026-02-28T10:00:00Z",
  },
  {
    id: "5",
    slug: "ebook-logistica-internacional",
    title: "E-book: Logística Internacional Descomplicada",
    description: "Tudo sobre Incoterms, modais de transporte e estratégias para otimizar sua cadeia logística.",
    type: "ebook",
    coverImage: "https://placehold.co/300x400/41AE32/FFFFFF?text=E-book+Logística",
    downloadUrl: "#",
    publishedAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "6",
    slug: "infografico-incoterms",
    title: "Infográfico: Guia Visual dos Incoterms 2020",
    description: "Comparativo visual de todos os Incoterms com responsabilidades de comprador e vendedor.",
    type: "infografico",
    coverImage: "https://placehold.co/300x400/6ED161/FFFFFF?text=Incoterms",
    downloadUrl: "#",
    publishedAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "7",
    slug: "guia-radar-siscomex",
    title: "Guia: Habilitação no RADAR SISCOMEX",
    description: "Passo a passo completo para habilitar sua empresa no RADAR e começar a importar.",
    type: "guia",
    coverImage: "https://placehold.co/300x400/2A7221/FFFFFF?text=Guia+RADAR",
    downloadUrl: "#",
    publishedAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "8",
    slug: "pdf-termos-comex",
    title: "Dicionário de Termos do Comércio Exterior",
    description: "Glossário completo com mais de 200 termos e siglas utilizados no comércio exterior brasileiro.",
    type: "pdf",
    coverImage: "https://placehold.co/300x400/033860/C4EDC0?text=Dicionário+Comex",
    downloadUrl: "#",
    publishedAt: "2026-02-05T10:00:00Z",
  },
];

export const launches: Launch[] = [
  {
    id: "1",
    title: "Mainô 4.0: Nova Plataforma de Gestão de Importações",
    description: "Conheça todas as novidades da versão 4.0 do Mainô, com dashboards avançados e integração automática com SISCOMEX.",
    type: "video",
    thumbnail: "https://placehold.co/640x360/092441/A3C9F0?text=Mainô+4.0",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: "12:34",
    publishedAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "2",
    title: "Calculadora de Importação: Tutorial Completo",
    description: "Aprenda a usar a calculadora de importação do Mainô para simular custos com precisão.",
    type: "video",
    thumbnail: "https://placehold.co/640x360/1C5B99/FFFFFF?text=Tutorial+Calculadora",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: "08:45",
    publishedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "3",
    title: "Módulo de Reports Interativos",
    description: "Apresentação do novo módulo de reports interativos com dados em tempo real do mercado de importação.",
    type: "video",
    thumbnail: "https://placehold.co/640x360/2E73B8/FFFFFF?text=Reports+Interativos",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: "15:20",
    publishedAt: "2026-02-28T10:00:00Z",
  },
  {
    id: "4",
    title: "Integração com ERP: Como Configurar",
    description: "Guia em vídeo para configurar a integração do Mainô com os principais ERPs do mercado.",
    type: "video",
    thumbnail: "https://placehold.co/640x360/033860/A3C9F0?text=Integração+ERP",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: "20:15",
    publishedAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "5",
    title: "Comex Cast #42: O Futuro da Importação no Brasil",
    description: "Entrevista com especialistas sobre as tendências do comércio exterior brasileiro para os próximos anos.",
    type: "podcast",
    thumbnail: "https://placehold.co/640x360/092441/6ED161?text=Comex+Cast+42",
    embedUrl: "#",
    duration: "45:30",
    publishedAt: "2026-03-18T10:00:00Z",
  },
  {
    id: "6",
    title: "Comex Cast #41: Reforma Aduaneira em Debate",
    description: "Análise profunda das mudanças na legislação aduaneira e o impacto para importadores.",
    type: "podcast",
    thumbnail: "https://placehold.co/640x360/1C5B99/C4EDC0?text=Comex+Cast+41",
    embedUrl: "#",
    duration: "38:20",
    publishedAt: "2026-03-04T10:00:00Z",
  },
  {
    id: "7",
    title: "Comex Cast #40: Logística Internacional Pós-Pandemia",
    description: "Como o mercado de fretes e logística internacional se transformou e quais são as novas dinâmicas.",
    type: "podcast",
    thumbnail: "https://placehold.co/640x360/2E73B8/FFFFFF?text=Comex+Cast+40",
    embedUrl: "#",
    duration: "52:10",
    publishedAt: "2026-02-18T10:00:00Z",
  },
  {
    id: "8",
    title: "Comex Cast #39: Acordo Mercosul-UE e seus Impactos",
    description: "Especialistas debatem as oportunidades e desafios do acordo comercial entre Mercosul e União Europeia.",
    type: "podcast",
    thumbnail: "https://placehold.co/640x360/033860/FFFFFF?text=Comex+Cast+39",
    embedUrl: "#",
    duration: "41:55",
    publishedAt: "2026-02-04T10:00:00Z",
  },
];

export const reports: Report[] = [
  {
    id: "1",
    slug: "panorama-importacoes-q1-2026",
    title: "Panorama das Importações Brasileiras - Q1 2026",
    description: "Análise completa do desempenho das importações brasileiras no primeiro trimestre de 2026, com dados setoriais e tendências.",
    coverImage: "https://placehold.co/600x400/092441/A3C9F0?text=Report+Q1+2026",
    content: `# Panorama das Importações Brasileiras - Q1 2026\n\n## Resumo Executivo\n\nAs importações brasileiras no primeiro trimestre de 2026 totalizaram USD 62,4 bilhões, representando um crescimento de 8,3% em relação ao mesmo período de 2025.\n\n## Principais Produtos Importados\n\n- Combustíveis e lubrificantes: USD 12,8 bi\n- Máquinas e equipamentos: USD 10,2 bi\n- Produtos químicos: USD 8,5 bi\n\n## Principais Parceiros Comerciais\n\nA China manteve sua posição como maior parceiro comercial, seguida pelos EUA e Alemanha.`,
    publishedAt: "2026-03-25T10:00:00Z",
  },
  {
    id: "2",
    slug: "relatorio-cambio-importacoes-2026",
    title: "Impacto do Câmbio nas Importações 2026",
    description: "Como as variações cambiais estão afetando os custos de importação e estratégias para mitigação de risco.",
    coverImage: "https://placehold.co/600x400/1C5B99/FFFFFF?text=Câmbio+Importações",
    content: `# Impacto do Câmbio nas Importações 2026\n\n## Cenário Atual\n\nO dólar americano iniciou 2026 com volatilidade elevada, impactando diretamente os custos de importação brasileiros.\n\n## Estratégias de Hedge\n\nEmpresas que adotaram estratégias de hedge cambial no início do ano conseguiram proteger suas margens significativamente.`,
    publishedAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "3",
    slug: "setores-mais-importados-2025",
    title: "Setores Mais Ativos em Importação - Retrospectiva 2025",
    description: "Análise dos setores econômicos com maior volume de importações em 2025 e perspectivas para 2026.",
    coverImage: "https://placehold.co/600x400/2E73B8/FFFFFF?text=Setores+Importação",
    content: `# Setores Mais Ativos em Importação - 2025\n\n## Tecnologia em Alta\n\nO setor de tecnologia liderou as importações em 2025, com destaque para semicondutores e equipamentos de telecomunicações.\n\n## Agronegócio\n\nO agronegócio manteve volumes elevados de importação de insumos, especialmente fertilizantes e defensivos agrícolas.`,
    publishedAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "4",
    slug: "guia-regimes-aduaneiros-especiais",
    title: "Report: Regimes Aduaneiros Especiais e suas Vantagens",
    description: "Análise detalhada dos regimes aduaneiros especiais disponíveis e como utilizá-los para otimizar custos.",
    coverImage: "https://placehold.co/600x400/033860/C4EDC0?text=Regimes+Especiais",
    content: `# Regimes Aduaneiros Especiais\n\n## O que são Regimes Especiais\n\nOs regimes aduaneiros especiais permitem a importação com suspensão ou isenção de tributos, mediante cumprimento de condições específicas.\n\n## Drawback\n\nO drawback é o regime mais utilizado por exportadores que importam insumos, permitindo a suspensão ou isenção dos tributos.`,
    publishedAt: "2026-02-10T10:00:00Z",
  },
];

export const siscomexUpdates: SiscomexUpdate[] = [
  {
    id: "1",
    title: "Nova versão do Portal Único do Comércio Exterior disponível",
    description: "A Receita Federal lançou a versão 3.2 do Portal Único, com melhorias na interface e desempenho no processamento de DIs.",
    type: "nova_funcionalidade",
    date: "2026-03-22T10:00:00Z",
    source: "https://www.gov.br/receitafederal",
  },
  {
    id: "2",
    title: "Manutenção programada do SISCOMEX - 28/03/2026",
    description: "O SISCOMEX ficará indisponível das 22h do dia 28/03 às 06h do dia 29/03 para manutenção de infraestrutura.",
    type: "manutencao",
    date: "2026-03-20T10:00:00Z",
    source: "https://www.gov.br/receitafederal",
  },
  {
    id: "3",
    title: "Atualização das alíquotas do II para produtos de informática",
    description: "Entraram em vigor as novas alíquotas do Imposto de Importação para produtos de informática conforme Resolução CAMEX nº 15/2026.",
    type: "atualizacao",
    date: "2026-03-15T10:00:00Z",
    source: "https://www.gov.br/mdic",
  },
  {
    id: "4",
    title: "Integração do SISCOMEX com o sistema da ANVISA ampliada",
    description: "A integração entre o SISCOMEX e o sistema da ANVISA foi ampliada para cobrir mais categorias de produtos sujeitos à vigilância sanitária.",
    type: "nova_funcionalidade",
    date: "2026-03-10T10:00:00Z",
    source: "https://www.gov.br/receitafederal",
  },
  {
    id: "5",
    title: "Atualização da Tabela NCM - Vigência a partir de 01/04/2026",
    description: "A SECEX publicou as alterações da tabela NCM que entrarão em vigor em 1º de abril de 2026.",
    type: "atualizacao",
    date: "2026-03-05T10:00:00Z",
    source: "https://www.gov.br/mdic",
  },
  {
    id: "6",
    title: "Manutenção emergencial do módulo de DI",
    description: "O módulo de registro de Declarações de Importação passou por manutenção emergencial para corrigir instabilidade reportada por usuários.",
    type: "manutencao",
    date: "2026-02-25T10:00:00Z",
    source: "https://www.gov.br/receitafederal",
  },
  {
    id: "7",
    title: "Novo módulo de acompanhamento de parametrização disponível",
    description: "Importadores podem agora acompanhar em tempo real o status de parametrização de suas DIs pelo novo módulo no Portal Único.",
    type: "nova_funcionalidade",
    date: "2026-02-18T10:00:00Z",
    source: "https://www.gov.br/receitafederal",
  },
  {
    id: "8",
    title: "Atualização da lista de países com tratamento especial",
    description: "O MDIC atualizou a lista de países beneficiários de tratamento tarifário preferencial no âmbito do SGP.",
    type: "atualizacao",
    date: "2026-02-10T10:00:00Z",
    source: "https://www.gov.br/mdic",
  },
];
